# https://taskfile.dev

version: '3'

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app
    aliases: [android]
  k8s:
    taskfile: ./k8s/Taskfile.yml
    dir: ./k8s
    aliases: [kubernetes, deploy]

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Show available tasks
    cmds:
      - echo "{{.GREETING}}"
      - echo ""
      - echo "Available task namespaces:"
      - echo "  backend:* - Backend Go server tasks"
      - echo "  app:* (or android:*) - Android app tasks"
      - echo "  k8s:* (or deploy:*) - Kubernetes deployment tasks"
      - echo ""
      - echo "Common workflows:"
      - echo "  task backend:dev     - Run backend in development mode"
      - echo "  task app:dev         - Android development workflow"
      - echo "  task k8s:deploy      - Full deployment to Kubernetes"
      - echo "  task k8s:redeploy    - Rebuild and redeploy backend"
      - echo "  task k8s:status      - Show Kubernetes resource status"
      - echo "  task k8s:logs:backend - Show backend logs"
      - echo ""
      - echo "Use 'task --list' to see all available tasks"
    silent: true

  dev:
    desc: Start both backend and Android development
    deps:
      - backend:swagger
    cmds:
      - echo "Starting development environment..."
      - echo "Backend - http://localhost:8080"
      - echo "Swagger docs - http://localhost:8080/swagger/"
      - echo ""
      - echo "To run Android app:"
      - echo "  task app:dev"

  test:
    desc: Run all tests (backend + Android)
    cmds:
      - task: backend:test
      - task: app:test

  clean:
    desc: Clean all build artifacts
    cmds:
      - task: backend:clean
      - task: app:clean

  build:
    desc: Build both backend and Android app
    cmds:
      - task: backend:build
      - task: app:build

  deploy:
    desc: Deploy to Kubernetes (full workflow)
    cmds:
      - task: k8s:deploy

  redeploy:
    desc: Rebuild and redeploy backend to Kubernetes
    cmds:
      - task: k8s:redeploy

  status:
    desc: Show Kubernetes deployment status
    cmds:
      - task: k8s:status

  logs:
    desc: Show backend logs from Kubernetes
    cmds:
      - task: k8s:logs:backend
