linters-settings:
  errcheck:
    exclude-functions:
      - (io.Writer).Write
      - (*encoding/json.Encoder).Encode
      - (crypto/rand.Read)

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell

run:
  timeout: 5m
