services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: days
      POSTGRES_PASSWORD: password
      POSTGRES_DB: days
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: