/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.germainleignel.days.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.germainleignel.days.api.models.HandlersErrorResponse

class HandlersErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandlersErrorResponse
        //val modelInstance = HandlersErrorResponse()

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
