/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.germainleignel.days.api.models

import com.germainleignel.days.api.models.ServicesUserResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token 
 * @param user 
 */
@Serializable

data class ServicesLoginResponse (

    @SerialName(value = "token")
    val token: kotlin.String? = null,

    @SerialName(value = "user")
    val user: ServicesUserResponse? = null

) {


}

