/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.germainleignel.days.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param description 
 * @param id 
 * @param name 
 * @param updatedAt 
 * @param userId 
 */
@Serializable

data class ServicesCalendarResponse (

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String? = null,

    @SerialName(value = "user_id")
    val userId: kotlin.String? = null

) {


}

