/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.germainleignel.days.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.germainleignel.days.api.apis.AuthApi
import com.germainleignel.days.api.models.HandlersErrorResponse
import com.germainleignel.days.api.models.ServicesLoginRequest
import com.germainleignel.days.api.models.ServicesLoginResponse

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test apiAuthLoginPost
        should("test apiAuthLoginPost") {
            // uncomment below to test apiAuthLoginPost
            //val credentials : ServicesLoginRequest =  // ServicesLoginRequest | Login credentials
            //val result : ServicesLoginResponse = apiInstance.apiAuthLoginPost(credentials)
            //result shouldBe ("TODO")
        }

    }
}
