/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.germainleignel.days.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.germainleignel.days.api.apis.CalendarsApi
import com.germainleignel.days.api.models.HandlersErrorResponse
import com.germainleignel.days.api.models.ServicesCalendarResponse
import com.germainleignel.days.api.models.ServicesCreateCalendarRequest
import com.germainleignel.days.api.models.ServicesUpdateCalendarRequest

class CalendarsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalendarsApi
        //val apiInstance = CalendarsApi()

        // to test apiCalendarsGet
        should("test apiCalendarsGet") {
            // uncomment below to test apiCalendarsGet
            //val result : kotlin.collections.List<ServicesCalendarResponse> = apiInstance.apiCalendarsGet()
            //result shouldBe ("TODO")
        }

        // to test apiCalendarsIdDelete
        should("test apiCalendarsIdDelete") {
            // uncomment below to test apiCalendarsIdDelete
            //val id : kotlin.String = id_example // kotlin.String | Calendar ID
            //apiInstance.apiCalendarsIdDelete(id)
        }

        // to test apiCalendarsIdGet
        should("test apiCalendarsIdGet") {
            // uncomment below to test apiCalendarsIdGet
            //val id : kotlin.String = id_example // kotlin.String | Calendar ID
            //val result : ServicesCalendarResponse = apiInstance.apiCalendarsIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test apiCalendarsIdPut
        should("test apiCalendarsIdPut") {
            // uncomment below to test apiCalendarsIdPut
            //val id : kotlin.String = id_example // kotlin.String | Calendar ID
            //val calendar : ServicesUpdateCalendarRequest =  // ServicesUpdateCalendarRequest | Calendar update request
            //val result : ServicesCalendarResponse = apiInstance.apiCalendarsIdPut(id, calendar)
            //result shouldBe ("TODO")
        }

        // to test apiCalendarsPost
        should("test apiCalendarsPost") {
            // uncomment below to test apiCalendarsPost
            //val calendar : ServicesCreateCalendarRequest =  // ServicesCreateCalendarRequest | Calendar creation request
            //val result : ServicesCalendarResponse = apiInstance.apiCalendarsPost(calendar)
            //result shouldBe ("TODO")
        }

    }
}
