/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.germainleignel.days.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.germainleignel.days.api.apis.UsersApi
import com.germainleignel.days.api.models.HandlersErrorResponse
import com.germainleignel.days.api.models.ServicesCreateUserRequest
import com.germainleignel.days.api.models.ServicesUserResponse

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test apiUsersIdGet
        should("test apiUsersIdGet") {
            // uncomment below to test apiUsersIdGet
            //val id : kotlin.String = id_example // kotlin.String | User ID
            //val result : ServicesUserResponse = apiInstance.apiUsersIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test apiUsersPost
        should("test apiUsersPost") {
            // uncomment below to test apiUsersPost
            //val user : ServicesCreateUserRequest =  // ServicesCreateUserRequest | User creation request
            //val result : ServicesUserResponse = apiInstance.apiUsersPost(user)
            //result shouldBe ("TODO")
        }

    }
}
