# Android App Taskfile
version: '3'

tasks:
  build:
    desc: Build Android app (debug)
    cmds:
      - .\gradlew.bat assembleDebug
    sources:
      - "**/*.kt"
      - "**/*.kts"
      - "app/src/**/*"
      - "gradle/**/*"
    generates:
      - "app/build/outputs/apk/debug/*.apk"

  build:release:
    desc: Build Android app (release)
    cmds:
      - .\gradlew.bat assembleRelease
    sources:
      - "**/*.kt"
      - "**/*.kts"
      - "app/src/**/*"
      - "gradle/**/*"
    generates:
      - "app/build/outputs/apk/release/*.apk"

  test:
    desc: Run Android unit tests
    cmds:
      - .\gradlew.bat test
      - echo "Unit tests completed!"

  test:instrumented:
    desc: Run Android instrumented tests (requires device/emulator)
    cmds:
      - .\gradlew.bat connectedAndroidTest
      - echo "Instrumented tests completed!"

  test:all:
    desc: Run all Android tests
    cmds:
      - task: test
      - task: test:instrumented

  lint:
    desc: Run Android lint checks
    cmds:
      - .\gradlew.bat lint
      - echo "Lint checks completed!"
      - echo "Check app/build/reports/lint-results.html for detailed results"

  clean:
    desc: Clean Android build artifacts
    cmds:
      - .\gradlew.bat clean
      - echo "Android build artifacts cleaned!"

  deps:
    desc: Download Android dependencies
    cmds:
      - .\gradlew.bat dependencies

  install:
    desc: Install debug APK to connected device
    cmds:
      - .\gradlew.bat installDebug
      - echo "Debug APK installed to device!"

  install:release:
    desc: Install release APK to connected device
    cmds:
      - .\gradlew.bat installRelease
      - echo "Release APK installed to device!"

  run:
    desc: Build and install debug APK, then start the app
    cmds:
      - task: install
      - echo "Starting app on device..."
      - adb shell am start -n com.germainleignel.days.debug/com.germainleignel.days.MainActivity

  bundle:
    desc: Build Android App Bundle (AAB) for Play Store
    cmds:
      - .\gradlew.bat bundleRelease
      - echo "Android App Bundle created!"
      - echo "Location - app/build/outputs/bundle/release/app-release.aab"

  check:
    desc: Run all Android checks (lint + test)
    cmds:
      - task: lint
      - task: test

  dev:
    desc: Development workflow - clean, build debug, install and run
    cmds:
      - task: clean
      - task: build
      - task: run

  devices:
    desc: List connected Android devices and emulators
    cmds:
      - adb devices -l
      - echo ""
      - echo "Tip - Use adb connect <ip>:5555 to connect to wireless debugging"
