// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Calendar struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ColorMeaning struct {
	ID         uuid.UUID    `json:"id"`
	CalendarID uuid.UUID    `json:"calendar_id"`
	ColorHex   string       `json:"color_hex"`
	Meaning    string       `json:"meaning"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type DayEntry struct {
	ID             uuid.UUID      `json:"id"`
	CalendarID     uuid.UUID      `json:"calendar_id"`
	Date           time.Time      `json:"date"`
	ColorMeaningID uuid.UUID      `json:"color_meaning_id"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
