name: Backend Tests (Simple)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: backend/go.sum

    - name: Install dependencies
      working-directory: ./backend
      run: go mod download

    - name: Run tests
      working-directory: ./backend
      env:
        GO_ENV: test
        JWT_SECRET: test-secret-for-github-actions
      run: |
        go vet ./...
        go test -v -race ./...

    - name: Build
      working-directory: ./backend
      run: go build ./...
