name: Android CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'app/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'app/**'
      - '.github/workflows/ci.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('app/**/*.gradle*', 'app/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      working-directory: ./app
      run: chmod +x gradlew
    
    - name: Run lint
      working-directory: ./app
      run: ./gradlew lint
    
    - name: Run unit tests
      working-directory: ./app
      run: ./gradlew test
    
    - name: Build release APK
      working-directory: ./app
      run: ./gradlew assembleRelease
    
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/app/build/outputs/apk/release/*.apk
    
    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: app/app/build/reports/lint-results*
