name: Full CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - name: Test Backend
      working-directory: ./backend
      env:
        GO_ENV: test
        JWT_SECRET: test-secret-for-github-actions
      run: |
        go mod download
        go vet ./...
        go test -v ./...
        go build -v ./...

  android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('app/**/*.gradle*', 'app/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Grant execute permission for gradlew
      working-directory: ./app
      run: chmod +x gradlew
    
    - name: Test Android
      working-directory: ./app
      run: |
        ./gradlew lint
        ./gradlew test

  # This job will only run if both backend and android jobs succeed
  status-check:
    runs-on: ubuntu-latest
    needs: [backend, android]
    if: always()
    
    steps:
    - name: Check overall status
      run: |
        if [ "${{ needs.backend.result }}" = "success" ] && [ "${{ needs.android.result }}" = "success" ]; then
          echo "✅ All tests passed!"
          exit 0
        else
          echo "❌ Some tests failed:"
          echo "  Backend: ${{ needs.backend.result }}"
          echo "  Android: ${{ needs.android.result }}"
          exit 1
        fi
